---
http_interactions:
- request:
    method: post
    uri: PLACEHOLDER_URL/entity/auth/login
    body:
      encoding: UTF-8
      string: '{"name":"PLACEHOLDER_USER","password":null}'
    headers:
      User-Agent:
      - Faraday v0.14.0
      Content-Type:
      - application/json
      Cookie:
      - ".ASPXAUTH=9C5457F82EA856C13F50ED7E1B1095EF6330CAFE04CA3A69B0AA8622DE94CA68E8AEB45C5DEC51BBAF431291FC5676F8C9AF2F643D047267E2F08B5196ECC08942F9C4BB4D1FC7F2B2A86028EAB5E6B25942976D5134BDB254AB8F36105B965468ABDBAEFDCA8C9DB5A61BEA34A00403E568611549C6E5744F943AB5653B20DCC1DC7571;
        ASP.NET_SessionId=cmuutgsimsemmt4x2uvsrksv; CompanyID=CCSTest; LegacyUI=0;
        Locale=Culture=en-US&TimeZone=GMTM0700A; UserBranch=1; requestid=13760"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 500
      message: Internal Server Error
    headers:
      Content-Type:
      - application/json; charset=utf-8
      Server:
      - Microsoft-IIS/8.5
      X-Handled-By:
      - Acumatica-PX.Export/AuthenticationManagerModule
      Set-Cookie:
      - LegacyUI=0; path=/
      - Locale=TimeZone=GMTM0700A&Culture=en-US; path=/
      - UserBranch=1; path=/
      - requestid=13761; path=/
      X-Powered-By:
      - ASP.NET
      Date:
      - Thu, 19 Apr 2018 02:07:58 GMT
      Content-Length:
      - '2806'
    body:
      encoding: UTF-8
      string: '{"message":"An error has occurred.","exceptionMessage":"Error: Invalid
        credentials. Please try again.","exceptionType":"PX.Data.PXException","stackTrace":"   at
        PX.Data.PXLogin.LoginUser(String& userName, String password)\r\n   at PX.Api.Services.LoginService.Login(String
        login, String password, String company, String branch, String locale, String
        prefix)\r\n   at PX.Api.ContractBased.WebApi.Controllers.AuthController.Login(Credentials
        credentials)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClassc.<GetExecutor>b__6(Object
        instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext
        controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}'
    http_version: 
  recorded_at: Thu, 19 Apr 2018 02:07:58 GMT
recorded_with: VCR 4.0.0
