---
http_interactions:
- request:
    method: post
    uri: PLACEHOLDER_URL/entity/auth/login
    body:
      encoding: UTF-8
      string: '{"name":"PLACEHOLDER_USER","password":null}'
    headers:
      User-Agent:
      - Faraday v0.15.0
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 500
      message: Internal Server Error
    headers:
      Content-Type:
      - application/json; charset=utf-8
      Server:
      - Microsoft-IIS/8.5
      X-Handled-By:
      - Acumatica-PX.Export/AuthenticationManagerModule
      Set-Cookie:
      - ASP.NET_SessionId=anqtshdtid113paeddm2ver1; path=/; HttpOnly
      - requestid=40975; path=/
      X-Powered-By:
      - ASP.NET
      Date:
      - Sat, 21 Apr 2018 01:15:34 GMT
      Content-Length:
      - '2806'
    body:
      encoding: UTF-8
      string: '{"message":"An error has occurred.","exceptionMessage":"Error: Invalid
        credentials. Please try again.","exceptionType":"PX.Data.PXException","stackTrace":"   at
        PX.Data.PXLogin.LoginUser(String& userName, String password)\r\n   at PX.Api.Services.LoginService.Login(String
        login, String password, String company, String branch, String locale, String
        prefix)\r\n   at PX.Api.ContractBased.WebApi.Controllers.AuthController.Login(Credentials
        credentials)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClassc.<GetExecutor>b__6(Object
        instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext
        controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n---
        End of stack trace from previous location where exception was thrown ---\r\n   at
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
        task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}'
    http_version: 
  recorded_at: Sat, 21 Apr 2018 01:15:34 GMT
recorded_with: VCR 4.0.0
